README.md
community-list.txt
plane-alert-db.txt

Moving to upper-case for ICAO. There was a mix of both, so I chose this.

spelling, standardize ICAO

---

badgers-best.csv
plane-alert-db.csv
plane-alert-gov.csv

Updated the link for PH-GOV -- note this is a specially appointed B737BBJ for use by the Dutch Royal Family and other govt VIPs, often used to shuttle the royal family around Europe.

Update PH-GOV link

---

.github/workflows/create_db_derivatives.yaml
.github/workflows/post_derivative_warning.yml
READ_BEFORE_MAKING_CHANGES.md

This commit adds a new github action that comments a warning to pull requests in which users try to change derivative databases.

ci: add derivative warning action

---

plane-alert-db.csv
plane_images.txt

Add photos for:
- AE54D5
- 3F9A92
- 3F4BA9
- AE119B
- 43C8EA
- 3F6F02
Correct Plane Type for 3D4365
- E200 instead of E300

AE54D5, 3F9A92, 3F4BA9, AE119B, 43C8EA, & 3F6F02 Photos; Correct 3D4365 Plane Type

---

plane_images.txt

Replaced invalid link for A406E3 and add additional photo.
Add Photos:
- ABC6BA
- ABD438
- AE146A

A406E3 Correct Invalid Link and Add new Photos, ABC6BA, ABD438, & AE146A Photos

---

.github/labeler.yml

Update labeler to not incorrectly apply the planes tag to a image only PR.

Update labeler.yml for recent plane_images extension change

---

.github/labeler.yml

Fix #225 the broke the labeler. Missing space between hypen and any. `-any` should be `- any`.

Correct yml spacing

---

plane-alert-db.csv
plane_images.csv

Set all planes with United States Marine Corps in the operator field to have that as category as well—previously most of them were in the United States Navy category.
Added 7500C5 / M48-02, a Malay government GLEX. Also added photos of same
Tweaked tags on some other Malay gov planes which were set to Civ rather than Gov.
Fixed plane type name on another GLEX
add colombian plane

this has been extremely frustrating

---

plane_images.csv

This callsign is now a LearJet but there is a nice photo of the 747 it used to be the database as well; this change removes the 747 photo.
https://airwaves.social/@overvabot/110673241144072316 <- One of these things is not like the other.
This removes 1 of the 3 photos of the above callsign from the photos csv.  I think the link above to the mastodon toot illustrates why.  There is a photo from 1984 showing the 747 this plane used to be, however the present registration is a LearJet.  This removes the old photo.

N540PA Remove photo of 1984 PanAM 747.

---

plane-alert-db.csv
plane_images.csv

TH-1s!
AE2936
AE2937
AE2938
AE2939
AE20BC
AE20BD
AE20BE
AE20BF
---
*introducing*
AE1849
AE4BE9
AE4BEA
AE4BEB
AE4BEC
and latecomer
AE4EB7
---
With pics on all but ae2938 because I couldn't find the tail code. Quite certain of these. Four of them flew in to KNEW yesterday, with some of them already in the mictronics database and two, ae2938 and ae20bf, not in mic's database. However, AE20BF was sending its tail code as its ADSB callsign, which matched sources elsewhere like helis.com. AE2938 was silent, so no idea what its code is. I added some others that were in Mic's database.
Also changed the two Bones added a while back to "USAF" instead of "United States Air Force" to match all the other USAF aircraft.

added USAF TH-1s: AE2936-39, AE20BC-F

---

plane-alert-db.csv

PLANE INFO:
Removed, aircraft is no longer registered to City of Phoenix:
A6FD30,N55BE
Added City of Phoenix PD:
A81A73,N621FB
A81E2A,N622FB
A8985E,N653FB
Added City of Mesa PD
A4FB3C,N42WB
A63EC8,N501MP
A64DA4,N505MP
A6515B,N506MP
Sources used: Name search or N-number search at https://registry.faa.gov/aircraftinquiry/Search/NameInquiry / https://registry.faa.gov/aircraftinquiry/Search/NNumberInquiry
Confirmed recent activity via FA where possible

Update Phoenix PD, add Mesa PD, add Arizona DPS aircraft

---

plane-alert-db.csv
plane_images.csv

Photos for AE1456
Photos for A33EB6
Photos for A585CA
Removed A4BC53 - Private Plane, incorrect data
Photos for AE2F6D

Photos for AE1456, A33EB6, AE2F6D, & A585CA

---

plane-alert-db.csv

* added Tango model code to some jayhawks
* Changed 6043 to Frankenhawk ([source](https://web.archive.org/web/20140427082128/http://www.uscg.mil/innovation/sci_tech_2010.asp))
* Changed USCG SH-60s to MH-60Ts (they're all converted)
* Changed USN MH-60R tags; these are ASW/ASuW multirole borbs, not CASEVAC/Slick/CSAR/&c
As noted in Discord, some of these Jayhawks' tails are duplicated, 6004/`AE67F4` and 6030/`AE680D` and maybe others besides—I didn't spend much time hunting. I think these hexes were some of the earlier(?) Jayhawks and have been retired one way or the other. `AE67Fx` and `AE680x` blocks seem to be used by P-8s for tactical codes these days. Perhaps we should change these hexes in the DB accordingly

Blankhawk tweaks

---

plane-alert-db.csv

Firefighting overhaul
* Category `Sam Tân` removed in favor of `Aerial Firefighter`
* `Hot Hot Hot` and `Hot Hot Hot Hot` tags replaced
* Rearranged tags where `Aerial Firefighter` would appear twice
* Added `Air Attack` or `Wildfire` where necessary
* Made sure DC-10s weren't listed as Super Scoopers, this is apparently very important to me
I made an attempt to ensure tags wouldn't appear twice (regex search in VS Code) and I think I got it. Does need a second pair of eyes because **you know Dziban**

Worked on firefighting aircraft tags

---

scripts/create_db_derivatives.py

Remove ICAOs that linger in the images file if they are removed from the DB files.

Remove image ICAOs without matching DB entry

---

plane_images.csv

add pics for ae60d3.
Also realized that fixing the capitalization of 4B9030 in plane-alert-db.csv did not propagate to plane_images.csv, but rather, it created a new entry for it while preserving the `4b9030` entry. So I just deleted the empty one and fixed the capitalization on the extant one with pics.
- [😬] I have performed a self-review of my code.

add pics for ae60d3, fix 4b9030 in plane_images.csv

---

plane-alert-db.csv
plane_images.csv

T-45 Hawks, most with pics
AE6284
AE62B5
AE62D1
AE62D5
AE62E5
AE62F8
From RB's last few days of hits.
AE6284 was in the database as a P-8 tactical, but looking back through August all I'm seeing it as is the Hawk, which given where it's been, what it's been doing, and the [callsign it's been using](https://henney.com/chm/callsign.htm) (BLZR, VT-21/VT-22 out of NAS Kingsville) is probably correct. I didn't see the hex appear anywhere Poseidony.
- [🦅] I have performed a self-review of my code.
- [🐱‍🐉] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

add some hawx

---

plane-alert-db.csv
plane_images.csv

PLANE INFO: Added a GAF C-130. It flew south of my station in Munster, Ireland and I didn't get an alert, so I figured I should add it. Info from:
https://www.planespotters.net/photo/1302821/5502-luftwaffe-german-air-force-lockheed-martin-c-130j-30-hercules
https://www.ads-b.nl/index.php?pageno=1002
- [ x] I have performed a self-review of my code.

Add a GAF C130, 55+02 and photos

---

plane-alert-db.csv
plane_images.csv

ae6357 - new lakota, no pics
ae6d75 - first t-7 in the database
ae0e1e - old blackhawk. very little info on this one, probably alabamer national guard, assuming it was upgraded to L model
924924 - a Goshawk. Some other planes were using this a few years back but this T-45 out of pensacola is the only one recently, I've seen it several times. Always rocks the ROKT callsign

add ae6357 ae6d75 ae0e1e 924924

---

plane-alert-db.csv

Looking at the FAA registration for this plane, it looks like it's registered to PPG.  Which is a paint company, not the Government of Tanzania.  This switches the fields to make it a bizjet but certainly change the tags or whatnot to something more creative :).

Update PPG plane to be paints, not government of Tanzania
