- community-list.txt
- F-GXLG - Beluga XL #1
- F-GXLH - Beluga XL #2
- F-GSTB - Beluga #2
> Add 3 Airbus Beluga/Beluga XL.

- community-list.txt
Hi, found this one:
N117GA - The last airworthy Boeing C-97 Stratofreighter nicknamed "Angel of Deliverance".
> Add N117GA.

- plane-alert-WiP.csv
As per title and as discussed in discord
> updated wip with outstanding discord lists

- plane-alert-search-terms-to-do.csv
- plane-alert-wip.csv
> USMC added

- plane-alert-search-terms-to-do.csv
- plane-alert-wip.csv
Ministry, Administration, Guardia, Force (removed USAF and RAF from added list)
> Multiple Search Terms added

- plane-alert-wip.csv
> ICAO correction 4B7F45

- plane-alert-db.csv
This will automatically pull in the corresponding aircraft silhouettes in Plane-Alert
> change 8th field in header to "ICAO Type"

- plane-alert-db.csv
> Added N1DC to plane-alert-db.csv

- README.md
This PR makes sure the database change warning is more visible.
> docs: put database warning in a MD admonition

- plane-alert-db.csv
Test whether the action works.
> test: test create derivatives github action

- plane-alert-db.csv
Reverts sdr-enthusiasts/plane-alert-db#79
> Revert "test: test create derivatives github action"

- .github/workflows/create_db_derivatives.yaml
- scripts/create_db_derivatives.py
Ensures that the images derivative db of the [plane-alert-ukraine.csv](https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/plane-alert-ukraine.csv) file is created.
> ci: make sure ukraine images db is cdreated

- plane-alert-ukraine.csv
- scripts/create_db_derivatives.py
Fix the ukraine plane list header.
> fix: fix ukraine database header

- scripts/check_main_databases.py
This pull request makes sure that the database check action fails when somebody enters an incorrect hex in the `$ICAO` column.
> add icao hex check

- scripts/check_main_databases.py
This pull request fixes the database check action and adds a check to see if the ICAO values are valid hexidecimals.
> ci: fix 'check_main_databases' action

- .github/workflows/check_derivatives_change.yml
This commit tries to fix the `check_derivatives_change` action by
pinning the version of the `changed-files` action.
> ci: fix check derivatives action

- .github/workflows/check_derivatives_change.yml
This PR fixes the `detected dubious ownership in repository at '/github/workspace'` warning (see https://github.com/sdr-enthusiasts/plane-alert-db/actions/runs/4382861013/jobs/7672404176).
> ci: improve derivatives check action

- .github/workflows/check_derivatives_change.yml
This pull request fixes the run condition of a step in the `check_derivatives_change` action.
> ci: fix action step run condition

- .github/workflows/check_derivatives_change.yml
This PR changes the derivative check action PR permission.
> ci: change derivative check action PR permission

- .github/workflows/check_derivatives_change.yml
> ci: try to fix check action permissions

- .github/workflows/check_derivatives_change.yml
> ci: remove contents permission

- .github/labeler.yml
- .github/workflows/check_derivatives_change.yml
> ci: fix derivative check action

- scripts/check_invalid_derivatives.py
Make sure that the output of `check_invalid_derivatives` is available.
> ci: fix check_derivatives_chagne action

- README.md
- READ_BEFORE_MAKING_CHANGES.md
I refactored the README a bit so it looks cleaner.
> docs: refactor README.md and replace SportsBanger links with local links

- plane_images.txt
> AE61CE Photos

- plane_images.txt
> A33266 Photos

- plane_images.txt
AE152F & A7DE71 Photos
A77B64 - Remove broken link and add 2 new photos
> AE152F, A7DE71, & A77B64 Photos

- plane_images.txt
> AE27F8 Photos

- plane-alert-db.csv
- plane_images.txt
> Add AE5681

- plane-alert-db.csv
- plane_images.txt
> Add AE08F9

- plane-alert-db.csv
- plane_images.txt
> Add A3DC2A (WK2) and Photos

- plane-alert-db.csv
- plane_images.txt
> 70C0B3 Photos, Add AE4821

- plane_images.txt
> 477FF3 Photos

- README.md
Created a new [Looker Studio](https://lookerstudio.google.com/overview) dashboard with distinct pages for each of the plane-alert lists. 
[plane-alert-db.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-db.csv)
[twitter-blocked.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-twitter-blocked.csv)
[ukraine.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-ukraine.csv)
[Dashboard](https://lookerstudio.google.com/reporting/46ff4328-09d3-4e65-ab5a-bd2ba27a18fd)
This would resolve #115
> Update README.md to include new looker studio link

- plane_images.txt
Add Photos for:
- AE1448
- AE1449
- AE1451
> AE1448, AE1449, & AE1451 Photos

- plane-alert-db.csv
- plane-alert-twitter-blocked.csv
Move Trump planes to twitter-blocked as plane-alerts are flagging users.
> Move DJT Planes to twitter-blocked

- plane_images.txt
> AE690E Photo

- plane_images.txt
> AE1452 & AE4BE0 Photos

- scripts/check_main_databases.py
Reenable the ICAO Hex check now that invalid ICAO has been resolved. This closes #121.
> activate valid ICAO Hexes check

- plane-alert-db.csv
- plane_images.txt
All corrections and additions in a separate branch without derivative creation script.
* Updated names of Chilean and Colombian presidents. 
* Corrected spelling of Colombia.
* Added:
* E8065E
* 0ACA78
* AE0451
* AE61D0
* AE6177
* Corrected photos:
* 0D088C
> Additions and corrections sans derivatives

- .github/labeler.yml
- .github/workflows/check_main_databases.yml
- .github/workflows/create_db_derivatives.yaml
- README.md
- READ_BEFORE_MAKING_CHANGES.md
- scripts/README.md
- scripts/check_invalid_derivatives.py
- scripts/check_main_databases.py
- scripts/create_db_derivatives.py
- scripts/create_images_reference.py
As explained by @dziban303 we run into strange line ending problems when editing the `plane_images.txt` file using the GitHub build in editor (see https://discord.com/channels/734090820684349521/810227340344819733/1100805463689396275). This PR will therefore change the file extension of this file, since this problem does not occur for CSV files.
> refactor: change plane_images.txt to CSV filetype

- plane-alert-db.csv
- plane_images.csv
* Added A0001D to plane-alert-db.csv
* Added images for A0001D and AE146E
* Fixed images for A0BE47
Doing PR again to appease github action gods 🐱‍👤
> added a0001d, added images for a0001d and ae146e, fixed pics for a0be47

- plane_images.csv
Correct Photos:
- E8CFC6
- AE27F2
- AE27F3
- AE27F4
- AE27F5
- AE27F6
- AE27F7
- AE27F9
- AE27FF
> Correct E8CFC6 and a whole bunch of H60 Photos

- plane-alert-db.csv
- plane_images.csv
Add AB9085 to database with pictures
> Add AB9085

- plane-alert-db.csv
- plane_images.csv
Pics for nasa talon acc30e, added a wiki link for adcca3 (and changed one of the tags, since I don't think this swami or whatever has much to do with jesus)
> Add pics for ACC30E, added wiki link for ADCCA3

- plane_images.csv
> 3F4D0C Photos

- plane_images.csv
A2AE0A / N242BG, one of melon's planes
> Add pics for n242bg

- plane_images.csv
Add photos for:
- AE10C1
- AE49C3
> Add photos for AE10C1 and AE49C3

- plane-alert-db.csv
- plane_images.csv
Added F-5N AE61D7 / 761568 with pics
> Added AE61D7 / 761568 w/pics

- plane_images.csv
> A19B53 Photos

- plane_images.csv
Add Photos for AE1459
Correct/Add Photo for AE269B
> Add Photos AE1459 and Correct AE269B

- plane_images.csv
> a7df20 pics

- plane_images.csv
> AE26A5 Photos

- plane_images.csv
Add photos for:
- AE26B2 :helicopter: 
- AE2FAE :airplane:
> Add AE26B2 and AE2FAE Photos

- plane_images.csv
pics for ae0259/98-5308
hurricane hunter without images? what in tarnation?
> pics for ae0259/98-5308

- plane_images.csv
> Add photos for AE2FA8

- plane_images.csv
Added pics for ae68b9, ae29da, ae1442, ae1455, ae1423, ae61c0
> Added pics for ae68b9, ae29da, ae1442, ae1455, ae1423, ae61c0

- plane_images.csv
Correct AE269A Photos :helicopter:
> Correct AE269A Photos

- plane_images.csv
C-17s ae1197, ae1198, ae119a, 03-3114, 03-3115, 03-3117
> add pics for ae119A, ae1198, ae119a

- plane_images.csv
Correct AE267A Photos :helicopter: 
Add Photos:
- ABB7DE
- AE2F56
> Correct AE267A Photos, Add ABB7DE & AE2F56 Photos

- plane-alert-milhuey-images.csv
- plane-alert-milhuey.csv
broken files were spawned. deleting.
> Removing broken files

- plane_images.csv
Add Photos for ABD081 & ABE314 - Top Aces F16-A :snake:
> Add Photos ABD081 & ABE314 Top Aces

- plane-alert-db.csv
- plane_images.csv
Add Photos for AE1236 - C-17A Globemaster :earth_americas: 
Modify tags for AE5772 :package:
> Add AE1236 Photos, modify tags for AE5772

- plane_images.csv
Add AE49C2 Photos - C-17A
Update AAA438 Photos
> Add AE49C2 Photos, Update AAA438 Photos

- plane-alert-db.csv
- plane_images.csv
Add photos for AE1532, fix registration.
Update ADFE98 tags.
> Add photos for AE1532, fix registration. Update ADFE98 tags.

- plane-alert-db.csv
Porting over additions from @kotahukka's PR #291
I've checked these against FAA n-number db, Radarbox, Flightaware, Mictronics db, @rikgale's VRS db, Jetphotos and/or Flickr, and twitter. A few in #291 were out of date and have been dropped entirely. A few more have been added.
Fixed capitalization issues, fixed displayed plane types, corrected ICAO plane types, changed some operator names, tweaked tags and categories.
Also adjusted a0001a and abe924 tags and categories to bring sanity to NFL team planes.
> Texas stuff

- plane-alert-db.csv
- plane_images.csv
Adding the two NE Patriots 767s
- A40B24
- A49138
> NE Patriots Planes

- plane_images.csv
fix ae1197 pic, add pics for ae1232 and ae1233
> ae1197 ae1232 ae1233

- plane_images.csv
Picless Planes from my station this week.
ae68ba, adfc9d, ae220e, a0b93d
> ae68ba, adfc9d, ae220e, a0b93d pics

- plane_images.csv
Correct photos for C04082. :ambulance:
> Correct Photos for C04082 :ambulance: 

- plane-alert-db.csv
- plane_images.csv
Add photos for:
- 400ECD
- 400EAA
Update tags for:
- 400EEA
> RAF Grob Tutors - 400ECD, 400EAA, & 400EEA

- plane_images.csv
New photos for A7C80B, removed bad links. :tractor:
> Update A7C80B Photos

- README.md
- plane-alert-db.csv
PLANE INFO: Walmart N45GH A57061
> Adding N45GH, A57061 as Walmart aircraft that was seen

- plane-alert-db.csv
PLANEINFO: A0F47B N1603M Adding San Antonio Police Department Helicopter https://www.flightaware.com/resources/registration/N1603M
PLANEINFO: A75995 N573AG Adding San Antonio Police Department Helicopter https://www.flightaware.com/resources/registration/N573AG
PLANEINFO: AB322C N820PM Adding San Antonio Police Department Helicopter https://www.flightaware.com/resources/registration/N820PM
> Adding San Antonio Police Department

- README.md
BUG FIX: Changing URLs from Sportsbadger to sdr-enthusiasts
> Updating to use SDR-Enthusiasts github url instead of sportsbadger

- plane-alert-db.csv
- plane_images.csv
Co-authored-by: pmd5700 <pmd5700@gmail.com>
Add photos from @pmd5700's review of PR #333
> Add planes and photos from PR #333

- plane-alert-db.csv
- plane_images.csv
Added Pictures:
96-5302
N30GJ
AE10E7
A340AX
Added Planes:
91-0512
94-00318
00-01051
19-5948
168097
> Fixed or added pictures and planes.

- plane-alert-db.csv
- plane_images.csv
added osprey 10-0055 / AE4EEE with pics
> AE4EEE w/pics

- plane-alert-db.csv
- plane_images.csv
Add A480A1
Correct Albatros spelling across DB
> Add A480A1

- plane-alert-db.csv
> add AE683E, a P-8 tactical

- plane_images.csv
Correct photos for A25952 :electric_plug: 
Correct photos for AE1CCE
> Correct photos for A25952 & AE1CCE

- plane_images.csv
Fix the AE1CC3 and AE1CCE swap from PR #349
> Fix AE1CC3 and AE1CCE

- plane-alert-db.csv
- plane_images.csv
Added:
n444741 n3n
n60795 vali
n25yr b25
n15797 t6
n2047 t6
n4447 t6
N1226N p40
n9820c t6
n566tx t6
n991vr t6
n4794n vali
n47tb dc3
n7300c t6
Did not add pics for everybody, though
> add some aircraft from Wings Over Houston

- plane-alert-db.csv
- plane_images.csv
> Add Missing Airlift Northwest Heli and Planes

- plane-alert-db.csv
- plane_images.csv
Added A638AD / N50MC. Relatively new acquisition by the city, can't find any pics yet.
> add a638ad / n50mc

- plane_images.csv
> A20747 Photos

- plane_images.csv
> Correct Photos for 48083D

- readme.mustache
Replace categories list with a table.
> Categories in table format

- plane_images.csv
> pics for N246PH / a24796

- .github/workflows/create_db_derivatives.yaml
- scripts/update_image_links.py
Add automatic replacement of '/400/' to '/full/' for a highly used image source. This will reduce review efforts and the amount of PR edits needed.
> Add '/400/' to '/full/' replacement for plane_images.csv

- plane_images.csv
> AA1DE9 Photos

- scripts/update_image_links.py
Update `update_image_links.py` to modify all image files.
> Update all image files for common error

- .github/workflows/create_db_derivatives.yaml
- scripts/update_image_links.py
Revert #378 
Reuse #376 and reorder `create_ db_derivatives.yaml`
Run workflow in a more efficient manner.
> Revert #378, Reuse #376, Reorder Workflow

- plane-alert-db.csv
- plane_images.csv
Add two P-8s, presumably tactical hexes. One visually confirmed to be a P-8, from a distance; the other is doing the same route out of Jacksonville to KNBG
Also changed some pics for DC-3T N932H/acedc6
> add two tacticool p-8s, fixpics for this DC-3T ACEDC6/n932h

- plane-alert-db.csv
- plane_images.csv
Added/fixed pictures: A0FE6E
Added aircraft with pictures: AE6407, AE6401, AE63F9, AC4456, 480C1B, A54941, ADFDCF, A008EF 
Deleted A0FE3B - No Ties to Elon Musk
> Added and fixed planes and pictures.

- plane-alert-db.csv
- plane_images.csv
CL60 3c0e3d / D-AUKE added, with pics. kx1t sez:
> Looks like they are using it for stem cell transport across the globe for bone marrow transplants for cancer patients
> added 3c0e3d and pics for kx1t

- plane_images.csv
> Updated photos for A745E8

- plane-alert-db.csv
PLANE INFO: 
AE60D3,168667,United States Marine Corps,Bell MV-22B Osprey
> Add AE60D3,168667,United States Marine Corps,Bell MV-22B Osprey

- plane-alert-db.csv
Changed `Dont`s to `Don't`s, made some changes to tags
- [🦜] I have performed a self-review of my code.
- [🏴‍☠️] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.
> clean up punctuation, adjust some tags

- plane-alert-db.csv
- plane_images.csv
add a744bd/n568bb with a pic
- [🤷‍♀️] I have performed a self-review of my code.
- [🛳] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.
> add a744bd/n568bb

- plane_images.csv
Add photos for 3B75DD
Remove airfighters photo for ADFD11
> Add photos for 3B75DD

- plane-alert-db.csv
- plane_images.csv
add the DC Aerial Photos planes for rhizo
- [📸] I have performed a self-review of my code.
- [💤] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.
> add a121b2/n172md and a96a98/n7058g

- plane_images.csv
pics for flying antenna farm RC-12X ae120b/93-00699 (yes, 00699, ignore typo in commit title)
- [📡] I have performed a self-review of my code.
- [📶] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.
> pics for ae120b/93-00669

- scripts/update_image_links.py
Update 'update_images_links.py' with better logging and to be more robust for future updates.
> Update 'update_images_links.py' - better logging

- plane-alert-db.csv
- plane_images.csv
Add:
- AA5187, unable to find photos.
- ACCC81
- ADD207
- AE56D5 - no photos
- ADD817 - no photos
-
> Add AA5187, ACCC87, ADD207, ADD817, & AE56D5 

- plane-alert-db.csv
- plane_images.csv
Draco ae5b8d with pics and a bollinger s-76 ac9a7d without
> add ae5b8d and ac9a7d

- plane_images.csv
Update photos for A7F642 and AA5F4C
> Update photos for A7F642 and AA5F4C

- plane-alert-db.csv
- plane_images.csv
PLANE INFO:
Add MCSO Helicopters and Plane, Add Images
Sources:
https://registry.faa.gov/aircraftinquiry/Search/NNumberResult?NNumberTxt=812LE
https://registry.faa.gov/aircraftinquiry/Search/NNumberResult?NNumberTxt=977MS
https://registry.faa.gov/aircraftinquiry/Search/NNumberResult?NNumberTxt=1423W
> Add MCSO Helicopters and Plane

- plane-alert-db.csv
- plane_images.csv
Update 48041B Photos, Add AE6C17, AE5FE8, & AE5697
> Update 48041B Photos, Add AE6C17, AE5FE8, & AE5697

- plane-alert-db.csv
- plane_images.csv
Added ADFDD0, 080010 (miscode), AE483A with pics
Replaced URLs with short links, including some tinyurl ones already in use
Corrected typecode on a bunch of MC-12s, all based on King Air 350s
Used WP shortlinks for military BE20s and UC-35s
Corrected a UC-35 listed as USAF to US Army
- [💤] I have performed a self-review of my code.
> add adfdd0, 080010, ae483a with pics. bunch of URL changes. Fix types.

- plane-alert-db.csv
- plane_images.csv
added another th-57 with a pic
added pics for the very cool-looking Irish C-295
- [🍀] I have performed a self-review of my code.
> add ae5ec8 and pics for 4ca420

- plane-alert-db.csv
- plane_images.csv
Started out as adding one, turned into nine. But hey, all got pics, so this makes the Picless Percentage (PP) shrink
A0D65A, N153LM
A7096E, N55211
A98E39, N7147C
A9998D, N7178Q
A4B1A6, N401PJ
A6F4D0, N54739
A07165, N12796
A820F4, N62266
A36D83, N32RW
- [📸] I have performed a self-review of my code.
> bunch of SkyLens survey planes

- plane_images.csv
wolfhound pics
- [🐺] I have performed a self-review of my code.
> add pics for C-146s ae68af and ae68b6

- scripts/create_db_derivatives.py
Add sort actions to the main database and reference files when Pull Requests are merged. This cascades into all the relevant derivative files and is included in the existing `create_db_derivatives.py` script.
> Add sort actions to the main database, reference files, and derivative files.

- plane-alert-db.csv
- plane_images.csv
add ae4e01 w/pic
- [⚓] I have performed a self-review of my code.
> add ae4e01 w/pic

- plane-alert-db.csv
- plane_images.csv
Added Elon's new 737 - A0DAC5. Photo is accurate but has partially covered Air China markings. :cn: I am sure we can find better photos in the coming weeks.
> Elon's new 737

- plane-alert-db.csv
- plane_images.csv
replaced two pics on jim carrey's Gulfstream. One was enormous and the other was a shitty render
Fixed a few 'SeaRanger' -> 'Sea Ranger' descriptions
Added two new TH-57Cs
Changed pics of that peeling E-6B 
- [✔] I have performed a self-review of my code.
> fix jim carrey's plane pics, added TH-57Cs, fixed descs, changed E-6B pix

- plane-alert-db.csv
- plane_images.csv
Adding four additional GAF C30J. Last two are KC-130J, but not able to find photos. Thanks for PR #456 @natexornate! This lead me to the below.
- 3E80C0
- 3E8182
- 3E875E
- 3E8764
> Additional GAF C30J

- plane-alert-db.csv
- plane_images.csv
ae627d ae6810 ae684c ae041a ae6802 ae1386 ae5ecc ae5eed ae6916
pics: ae041a ae5ecc ae5eed ae6916 ae1386
removed broken pics from 40729D
> add ae627d ae6810 ae684c ae041a

- plane-alert-db.csv
- plane_images.csv
> add a98455

- plane-alert-db.csv
- plane_images.csv
ae5f3d, ae67f1, ae0c7f, ae0096, new aussie mq-4 af3c53 which will certainly change hex once it moves down under
picks for all except the unknown P-8
I did not spend a lot of time on the UH-60, just not worth more than 2 minutes of googling for these old birds
> add ae5f3d ae67f1 ae0c7f ae0096 af3c53

- plane-alert-db.csv
- plane_images.csv
adfee1 ae63d4 ae0058
all w/pics
> add adfee1 ae63d4 ae0058

- plane-alert-db.csv
from discord. also changed instances of 'black hawk' to 'blackhawk'
> some additions

- plane-alert-db.csv
american goodyear blimps plus a missing gulfstream
also changed the one blimp in the db to use icao type SHIP rather than N07
> add goodyear zepps

- plane-alert-db.csv
Reverts sdr-enthusiasts/plane-alert-db#478
> Revert "add goodyear zepps"

- plane-alert-db.csv
Dunno what's going on here. This should fix it.
> change N2A to SHIP

- plane-alert-db.csv
- plane_images.csv
Added Irish Air Corps' second C-295, 284. The first, 285 was already in the DB.
- [x ] I have performed a self-review of my code.
> Add 4CA41F Irish Air Corps C295 reg 284

- plane-alert-db.csv
- plane_images.csv
i actually added photos for a change
> add ae0631 ae0181 a5236f

- plane-alert-db.csv
- plane-alert-vulcanization-images.csv
- plane-alert-vulcanization.csv
> Add ICAO Type to A1DF3E

- plane-alert-db.csv
> Set AE61F6 to AC-130J

- plane-alert-db.csv
- plane_images.csv
Add AE20FD with photos. :bear:
> Add AE20FD with photos

- plane-alert-do a barrel roll-images.csv
- plane-alert-do a barrel roll.csv
Remove erroneously created files
> Remove erroneously created files

- plane-alert-db.csv
- plane_images.csv
add N946MM, legalizer of weeds
fix pics for ABA4FE and E8CFB9
- [🌿] I have performed a self-review of my code.
> fixes, one addition

- plane-alert-db.csv
- plane_images.csv
kx1d's Mystery 757s and the other guy's family dollar plane which he decided not to add rather than make a small fix 🤷‍♀️
> add mystery 757s and the family dollar plane

- plane-alert-db.csv
- plane_images.csv
new t-54, t-45, several uh60s, p-8, th73. added mfg to other t-54 type names. fixed broken pic.
> fix broken pic, seven additions

- plane-alert-db.csv
- plane_images.csv
fix some T-45s
add some T-45s
fix a fokker
add some fokkers
> additions and fixes

- plane_images.csv
added some missing pics, fixed pics for n802na
> fixed some pics

- README.md
- plane_images.csv
> Added Picture for C6054

- plane-alert-db.csv
- plane_images.csv
neat NP-3D with a weird tail, some others
> add NP-3D, some hawx, an hc-144 and a u-28

- plane-alert-db.csv
- plane_images.csv
> added two new EA-37s with what pics I could find

- plane_images.csv
> images fix (were all wrong)

- plane-alert-db.csv
- plane_images.csv
0D0F1E Quintana Roo Police Helicopter 
0D078C Mexican Airforce VIP Helicopter 
-  I have performed a self-review of my code.
-  While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.
> New Database Entries 

- plane-alert-db.csv
- plane_images.csv
> the rest of the potato roll planes

- plane-alert-categories.csv
- plane-alert-db.csv
- plane_images.csv
0D0F1E & 0D078C: entries corrected missing tags
0D077E: new in db
> 0D077E Heli added, items corrected

- plane-alert-db.csv
- plane_images.csv
> they're on a mission from god

- plane-alert-db.csv
- plane_images.csv
- scripts/check_categories.py
> couple more

- plane-alert-db.csv
- plane_images.csv
some ospreys, some texans, mukesh ambani, other stuff
> ospreys and mukesh ambani and others

- plane-alert-db.csv
- plane_images.csv
> some interesting finds this morning
